### ISSUE TITLE
主線程死亡

### ISSUE THREAD

**Issue by jason920612** [jason920612/YingLingdom-Network-Minecraft-Server#3]
[10:09:48 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:939) [?:?]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:887) ~[patched_1.16.5.jar:git-Airplane-"c060ef5"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:766) ~[patched_1.16.5.jar:git-Airplane-"c060ef5"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:858) ~[patched_1.16.5.jar:git-Airplane-"c060ef5"]
        at org.bukkit.craftbukkit.v1_16_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:29) ~[patched_1.16.5.jar:git-Airplane-"c060ef5"]

**Comment by jason920612** [comment]
還原為舊核心解決
